### ISSUE TITLE
consider the combination setuptools_scm + release via travis deploy

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-repeat#12]
just a consideration, i did the same for pytest-xdist yesterday and made a release that way as well

**Comment by tomviner** [comment]
Like it. Although I'd defer to the other maintainers, since I'm a noob here ;-)

**Comment by davehunt** [comment]
Thanks for the suggestion @RonnyPfannschmidt. I think I've set this up, and have pushed a tag so we'll see if it uploads a new release. If this works I'll consider setting it up for my other plugins.

**Comment by davehunt** [comment]
Here's the tag build in Travis: https://travis-ci.org/pytest-dev/pytest-repeat/builds/155074784

**Comment by davehunt** [comment]
I think it didn't like my password... it also tried deploying from two separate jobs. Here's another attempt: https://travis-ci.org/pytest-dev/pytest-repeat/builds/155082416

**Comment by davehunt** [comment]
It worked once I corrected the travis.slug value to be pytest-dev/pytest-repeat! See https://pypi.python.org/pypi/pytest-repeat/0.4.1

**Comment by tomviner** [comment]
Nice one @davehunt !
