### ISSUE TITLE
Enable Test Case Level Repeat Config

### ISSUE THREAD

**Issue by WoodenMug** [pytest-dev/pytest-repeat#13]
Hi,

Thanks for writing such a useful and simple to use plugin. I have been using repeat in our environment for a while and added support for test case level repeat configuration using markers. I was wondering if you are interested in this feature and us contributing back to your repo.

Thanks,
Rui

**Comment by tomviner** [comment]
Certainly sounds interesting. Are you talking about repeating by applying markers to parametrize values? Sort of how you can apply xfail to particular parametrize values?

Feel free to submit a PR, or give a link to your code, so we can discuss :smile:

**Comment by WoodenMug** [comment]
Hi @tomviner, Thanks for getting back to me.
I have created a PR here: https://github.com/pytest-dev/pytest-repeat/pull/14
Let me know how you think about it.
Thanks!
