### ISSUE TITLE
Repeat decorator

### ISSUE THREAD

**Issue by Peque** [pytest-dev/pytest-repeat#16]
Is it currently possible to mark a test with a decorator to be run multiple times?

In example:

```python
@pytest.repeat(10)
def test_repeated_10():
    assert True
```

So when executing `pytest` only the tests that are marked with the decorator are run multiple times.

**Comment by The-Compiler** [comment]
I see you opened https://github.com/pytest-dev/pytest-repeat/issues/16 already - I think this definitely should go to that plugin rather than pytest core.

**Comment by The-Compiler** [comment]
Argh! Nevermind me. I thought this was the core repository, my bad! 😆

**Comment by shreyashah** [comment]
Do we have this repeat decorator?

**Comment by RonnyPfannschmidt** [comment]
no

**Comment by shreyashah** [comment]
any plans to bring it in?

**Comment by The-Compiler** [comment]
This is all voluntary work, so if nobody steps up, nothing will happen :wink: Help welcome!

**Comment by nicoddemus** [comment]
If anyone wants to tackle this, it should be just a matter of changing this part of the code:

https://github.com/pytest-dev/pytest-repeat/blob/3d6230e88e51d4ac28c962c1e17d40987675aa58/pytest_repeat.py#L38-L39

To also get the mark from the `metafunc.function` object and use that if the mark is present:

```python
def pytest_generate_tests(metafunc):
    count = metafunc.config.option.count
    mark = metafunc.function.get_closest_mark('repeat')
    if mark:
        count = mark.args[0]
    ...
```

Plus tests and update the README.

(all the above is untested, but it shouldn't be far off)

**Comment by shreyashah** [comment]
Sure, let me try doing this and create a PR. Thanks.

**Comment by Peque** [comment]
See https://github.com/pytest-dev/pytest-repeat/pull/22.

@shreyashah Hope you do not mind. :blush:

**Comment by shreyashah** [comment]
@Peque : Oh absolutely, no! Thank you for bringing this in. I had this in my local env, but pushed to open a PR.
