### ISSUE TITLE
Support unittest.TestCase subclasses

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest-repeat#3]
I havent investigated the cause at all, but it doesnt work with https://github.com/wikimedia/pywikibot-core

e.g. the following only run the tests once

```
py.test-3.4 -vvvv --count=10 tests/date_tests.py
py.test-3.4 -vvvv --count=10 tests/diff_tests.py
```

(i'll attempt to make this easier to reproduce, but just want to get the problem logged to begin with)

**Comment by coagulant** [comment]
Works with test functions, does not work with unittest.TestCase for me.

**Comment by jayvdb** [comment]
Thanks.  Yes, that explains it.

**Comment by jayvdb** [comment]
@davehunt , I believe this isnt fixed. I run the same command, and still only have one set of tests run.
Is it impossible to support unittest.TestCase subclasses ?

Also, I do not see a set of warnings as mentioned in aeae41d3e2 when I run it with the above commands, because
1.  our tests use `unittest2`. I've got a local fix for this.
2.  it is a python warning, which are hidden by default if the test was successful. Ideally we use the pytest warning system.

**Comment by davehunt** [comment]
No, it's not 'fixed', but as far as I can tell there is no way to fix it currently. From [the documentation](http://pytest.org/latest/unittest.html):

> While pytest supports receiving fixtures via test function arguments for non-unittest test methods, unittest.TestCase methods cannot directly receive fixture function arguments as implementing that is likely to inflict on the ability to run general unittest.TestCase test suites.

If you can find a way to support unittest, then please feel welcome to open a pull request. Similarly, a pull request to display the appropriate warnings for unittest2 would be welcome.

**Comment by jayvdb** [comment]
Well, on the command line I can repeat the selection criteria and the tests will run multiple times, so maybe there is another way to do that in the plugin ...?

If we dont find a workaround for unittest subclasses, we need to find a way to use pytest warnings, rather than python warnings, as they are not visible, and the plugin's use of the python warning could break tests which are inspecting the warnings emitted by their own code.

**Comment by tomviner** [comment]
@jayvdb I can confirm that specifying test paths multiple times does the job, but not sure how to use that as an automated repeat method.

**Comment by RonnyPfannschmidt** [comment]
that collection runs multiple times is actually a pytest bug - test ids should be unique

**Comment by stas00** [comment]
Two possible solutions are `pytest-flakefinder` and a little hack script, both described here:
https://stackoverflow.com/a/63712502/9201239
