### ISSUE TITLE
Warnings not listed in https://docs.pytest.org/en/latest/warnings.html

### ISSUE THREAD

**Issue by kirankotari** [pytest-dev/pytest-repeat#34]
I am getting the following warnings and which is not listed in the below given link.

tests/test_functions.py::TestFun::test_add1
  /Users/xyz/.local/share/virtualenvs/mathlib_abc-WoXJe7Bq/lib/python3.7/site-packages/pytest_repeat.py:45: UserWarning: Repeating unittest class tests not supported
    "Repeating unittest class tests not supported")

tests/test_functions.py::TestFun::test_add2
  /Users/xyz/.local/share/virtualenvs/mathlib_abc-WoXJe7Bq/lib/python3.7/site-packages/pytest_repeat.py:45: UserWarning: Repeating unittest class tests not supported
    "Repeating unittest class tests not supported")

tests/test_functions.py::TestFun::test_mul
  /Users/xyz/.local/share/virtualenvs/mathlib_abc-WoXJe7Bq/lib/python3.7/site-packages/pytest_repeat.py:45: UserWarning: Repeating unittest class tests not supported
    "Repeating unittest class tests not supported")

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by RonnyPfannschmidt** [comment]
The pytest-repeat warnings are not part of pytest

**Comment by kirankotari** [comment]
1. Then why it's suggesting pytest warnings docs ? 
2. Any idea why repeating unittest class tests not supported ?

here is my test_function code
```
import unittest
from mathlib_abc import functions

class TestFun(unittest.TestCase):
    def test_add1(self):
        assert functions.add(1,2,3) == 6
```

**Comment by RonnyPfannschmidt** [comment]
@kirankotari pytest's warnings capture refers users to that documentation - the warnings you get however are not part of pytest itself
