### ISSUE TITLE
Using pytest.mark.repeat with pytest parametrize

### ISSUE THREAD

**Issue by tony-teknique** [pytest-dev/pytest-repeat#37]
I have been trying to repeat only one of the parameterised tests through `pytest.param`, but I have not been able to get anywhere. Is it a known limitation with the pytest-repeat plugin?

```
@pytest.mark.parametrize("name", 
[pytest.param("John", marks=pytest.mark.special), 
pytest.param("Ted", marks=pytest.mark.special), 
pytest.param("Ben", marks=pytest.mark.repeat(10))
])
def test_print_name(name):
    print(name)
```

**Comment by RonnyPfannschmidt** [comment]
Pytest-repeat cannot be used indirectly, as parameterization happens before the mark shows

**Comment by tony-teknique** [comment]
Thanks!
