### ISSUE TITLE
Repeat only on failure

### ISSUE THREAD

**Issue by varac** [pytest-dev/pytest-repeat#42]
I'd like to repeat a test until it succeeds (waiting for some condition before continuing with other tests). An option would be great like `--repeat-on=failure`, with a default of `success`, which seems to be the default behviour. Does this make sense ?

**Comment by The-Compiler** [comment]
Maybe the [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures/) plugin would be a better match?

**Comment by varac** [comment]
@The-Compiler Thxm  I already found and use pytest-rerunfailures after creating this issue. works great, still I think it could be a good addition for pytest-repeat. But feel free to close this issue.
