### ISSUE TITLE
Feature request:  class level repeat

### ISSUE THREAD

**Issue by adamf663** [pytest-dev/pytest-repeat#45]
I have a class where scripts are dependent on prior results.
For class C, scripts S1, S2, S3 to run in order.

Putting the pytest.mark.repeat on the class doesn't result in repeating the class, but in repeating each test N times.  
With '@pytest.mark.repeat(3)', the result is
C.S1, C.S1, C.S1, C.S2, C.S2, C.S2, C.S3, C.S3, C.S3.
What I need is:
C.S1, C.S2, C.S3, C.S1, C.S2, C.S3,...

**Comment by GabrielKis** [comment]
If I'm not wrong I think this feature already exists. Have you tried `--repeat-scope=class` when executing your tests?

**Comment by okken** [comment]
yes. Seems like `--repeat-scope=class` works. 
One problem is that `--repeat-scope` is undocumented in README. I've filed issue #61 to address that.

**Comment by okken** [comment]
This issue can be closed
