### ISSUE TITLE
How do I get the current number of repetitions in the setup_class function

### ISSUE THREAD

**Issue by panyicheng123** [pytest-dev/pytest-repeat#58]
I want to use an environment based on the number of repetitions
as the picture show 
![image](https://user-images.githubusercontent.com/51101265/190850532-bf087a63-b48f-42a4-88ad-2950c8a84b9d.png)

**Comment by panyicheng123** [comment]
Thanks everyone who can reply to me

**Comment by RonnyPfannschmidt** [comment]
its not clear why you do not use parametrize of the keys instead, as that gives you the key and correctly works on any case

its not safely possible to get the functon scope repeat value at the class level

th fact that ou absolutely need the environment extracted and the number of repeats match the key means that you dont want a repeat, you want a parametrize with class scope

**Comment by panyicheng123** [comment]
> its not clear why you do not use parametrize of the keys instead, as that gives you the key and correctly works on any case
> 
> its not safely possible to get the functon scope repeat value at the class level
> 
> th fact that ou absolutely need the environment extracted and the number of repeats match the key means that you dont want a repeat, you want a parametrize with class scope

thanks for your reply,i will try it.

**Comment by panyicheng123** [comment]
> its not clear why you do not use parametrize of the keys instead, as that gives you the key and correctly works on any case
> 
> its not safely possible to get the functon scope repeat value at the class level
> 
> th fact that ou absolutely need the environment extracted and the number of repeats match the key means that you dont want a repeat, you want a parametrize with class scope

Dear author hello,The previous problem has been solved, but now a new one has arisen, I have a test requirement that requires repeated execution of a test case, and the specified assertion is executed according to the current number of repetitions. How do I get the current number of repetitions

Looking forward to your reply！

Here is the example
![image](https://user-images.githubusercontent.com/51101265/225528595-e69c053a-9175-46f3-8462-ddd97b3e19c0.png)

**Comment by okken** [comment]
looks like this was resolved as not needed
