### ISSUE TITLE
this plugin can repeat cases after fliter by mark ?

### ISSUE THREAD

**Issue by smice-ICE** [pytest-dev/pytest-repeat#60]
when repeat a large times, collecting items will out of memory and killed by system, becasuse it repeat all cases then filter case

**Comment by RonnyPfannschmidt** [comment]
Currently it is impossible to do repeat after filter as filtering is applied after collection, and repeat is integrated with collection

A major change of pytest and its collection tree would be necessary to enable this

**Comment by smice-ICE** [comment]
thx, I got it and find another solution
