### ISSUE TITLE
switch to pyproject.toml 

### ISSUE THREAD

**Issue by okken** [pytest-dev/pytest-repeat#64]
and either flit-core or hatchling

**Comment by RonnyPfannschmidt** [comment]
Going hatch later will be way simpler thanks to the modern setup

**Comment by okken** [comment]
Do you recommend just switching to hatch now?

**Comment by okken** [comment]
since I'm already shaking things up a bit, why not a bit more?

**Comment by RonnyPfannschmidt** [comment]
Personally I recommend using hatch when its a fit
