### ISSUE TITLE
I'd like to help with this project

### ISSUE THREAD

**Issue by okken** [pytest-dev/pytest-repeat#66]
Hi @pytest-dev/pytest-repeat-admin, 

I was looking through this project recently and noticed it seems to need a bit of attention.  
I've filed a few issues, and also noticed that many of the current issues are old and could probably be closed. 

I'd like to contribute to the project with, at the very least

- tagging/labelling issues 
- closing some issues
- responding to issues

But also, I'd like to work on:

- resolving/implementing some of the issues/suggestions I've submitted.

Please let me know if that'd be possible.

**Comment by nicoddemus** [comment]
HI @okken,

Thanks a lot for the offer! From my part I'm more than happy to give you maintainer status here, given your numerous contributions to the pytest ecosystem.

I will wait a few days for @davehunt (the repo owner) to manifest, otherwise I will grant you access then.

Cheers.

**Comment by davehunt** [comment]
I fully support @okken being a maintainer of this project, thanks so much for the offer. @nicoddemus please feel free to go ahead and make the necessary changes.

**Comment by nicoddemus** [comment]
Added @okken to @pytest-dev/pytest-forked-developers; @okken let me know if you miss any permissions and I will make the necessary adjustments. 

Thanks everyone!

**Comment by okken** [comment]
Thank you everyone.
